version: '3'
services:
  dockerd:
    image: docker:dind
    privileged: true
    volumes:
      - dockerd-run-volume:/var/run
  daemon:
    build:
      context: .
      args:
        # Set via .env file.
        USE_HOST_VENDOR: "${USE_HOST_VENDOR}"
    volumes:
      # Use host's ssh key to access git remote
      - ~/.ssh/id_rsa:/root/.ssh/id_rsa
      - ./data:/opt/canary/data
      - dockerd-run-volume:/opt/dockerd/var/run
    environment:
      - CANARY_DATA=/opt/canary/data
      - DOCKER_HOST=unix:///opt/dockerd/var/run/docker.sock
    depends_on:
      - dockerd
    command: "./scripts/wait-for-dockerd.sh && ./canary"

volumes:
  dockerd-run-volume:
